#!/usr/bin/env bash

set -e

if [ "$(id -u)" != 0 ]; then
  echo "This script must be run as root. 'sudo $0'"
  exit 1
fi

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sudo apt install -y zsh curl git
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

